from collections import OrderedDict

VERSION_DATA = OrderedDict(
    [
        (
            "\u2014English (EN)\u2014",
            [
                "21st Century King James Version (KJ21)",
                "American Standard Version (ASV)",
                "Amplified Bible (AMP)",
                "Amplified Bible, Classic Edition (AMPC)",
                "BRG Bible (BRG)",
                "Common English Bible (CEB)",
                "Complete Jewish Bible (CJB)",
                "Contemporary English Version (CEV)",
                "Darby Translation (DARBY)",
                "Disciples\u2019 Literal New Testament (DLNT)",
                "Douay-Rheims 1899 American Edition (DRA)",
                "Easy-to-Read Version (ERV)",
                "English Standard Version (ESV)",
                "English Standard Version Anglicised (ESVUK)",
                "Expanded Bible (EXB)",
                "1599 Geneva Bible (GNV)",
                "GOD\u2019S WORD Translation (GW)",
                "Good News Translation (GNT)",
                "Holman Christian Standard Bible (HCSB)",
                "International Children\u2019s Bible (ICB)",
                "International Standard Version (ISV)",
                "J.B. Phillips New Testament (PHILLIPS)",
                "Jubilee Bible 2000 (JUB)",
                "King James Version (KJV)",
                "Authorized (King James) Version (AKJV)",
                "Lexham English Bible (LEB)",
                "Living Bible (TLB)",
                "The Message (MSG)",
                "Modern English Version (MEV)",
                "Mounce Reverse-Interlinear New Testament (MOUNCE)",
                "Names of God Bible (NOG)",
                "New American Bible (Revised Edition) (NABRE)",
                "New American Standard Bible (NASB)",
                "New Century Version (NCV)",
                "New English Translation (NET Bible)",
                "New International Reader's Version (NIRV)",
                "New International Version (NIV)",
                "New International Version - UK (NIVUK)",
                "New King James Version (NKJV)",
                "New Life Version (NLV)",
                "New Living Translation (NLT)",
                "New Revised Standard Version (NRSV)",
                "New Revised Standard Version, Anglicised (NRSVA)",
                "New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)",
                "New Revised Standard Version Catholic Edition (NRSVCE)",
                "New Revised Standard Version Updated Edition (NRSVUE)",
                "Orthodox Jewish Bible (OJB)",
                "Revised Standard Version (RSV)",
                "Revised Standard Version Catholic Edition (RSVCE)",
                "The Voice (VOICE)",
                "World English Bible (WEB)",
                "Worldwide English (New Testament) (WE)",
                "Wycliffe Bible (WYC)",
                "Young's Literal Translation (YLT)",
            ],
        ),
        (
            "\u2014\u6c49\u8bed (ZH)\u2014",
            [
                "Chinese Contemporary Bible (CCB)",
                "Chinese New Testament: Easy-to-Read Version (ERV-ZH)",
                "Chinese New Version (Simplified) (CNVS)",
                "Chinese New Version (Traditional) (CNVT)",
                "Chinese Standard Bible (Simplified) (CSBS)",
                "Chinese Standard Bible (Traditional) (CSBT)",
                "Chinese Union Version (Simplified) (CUVS)",
                "Chinese Union Version (Traditional) (CUV)",
                "Chinese Union Version Modern Punctuation (Simplified) (CUVMPS)",
                "Chinese Union Version Modern Punctuation (Traditional) (CUVMPT)",
            ],
        ),
        ("\u2014Amuzgo de Guerrero (AMU)\u2014", ["Amuzgo de Guerrero (AMU)"]),
        (
            "\u2014\u0627\u0644\u0639\u0631\u0628\u064a\u0629 (AR)\u2014",
            ["Arabic Bible: Easy-to-Read Version (ERV-AR)", "Ketab El Hayat (NAV)"],
        ),
        (
            "\u2014\u0905\u0935\u0927\u0940 (AWA)\u2014",
            ["Awadhi Bible: Easy-to-Read Version (ERV-AWA)"],
        ),
        (
            "\u2014\u0411\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 (BG)\u2014",
            [
                "1940 Bulgarian Bible (BG1940)",
                "Bulgarian Bible (BULG)",
                "Bulgarian New Testament: Easy-to-Read Version (ERV-BG)",
                "Bulgarian Protestant Bible (BPB)",
            ],
        ),
        (
            "\u2014Chinanteco de Comaltepec (CCO)\u2014",
            ["Chinanteco de Comaltepec (CCO)"],
        ),
        ("\u2014Cebuano (CEB)\u2014", ["Ang Pulong Sa Dios (APSD-CEB)"]),
        (
            "\u2014\u13e3\u13b3\u13a9 \u13a6\u13ec\u13c2\u13af\u13cd (CHR)\u2014",
            ["Cherokee New Testament (CHR)"],
        ),
        ("\u2014Cakchiquel Occidental (CKW)\u2014", ["Cakchiquel Occidental (CKW)"]),
        (
            "\u2014\u010ce\u0161tina (CS)\u2014",
            ["Bible 21 (B21)", "Slovo na cestu (SNC)"],
        ),
        ("\u2014Cymraeg (CY)\u2014", ["Beibl William Morgan (BWM)"]),
        (
            "\u2014Dansk (DA)\u2014",
            [
                "Bibelen p\xe5 hverdagsdansk (BPH)",
                "Dette er Biblen p\xe5 dansk (DN1933)",
            ],
        ),
        (
            "\u2014Deutsch (DE)\u2014",
            [
                "Hoffnung f\xfcr Alle (HOF)",
                "Luther Bibel 1545 (LUTH1545)",
                "Neue Genfer \xdcbersetzung (NGU-DE)",
                "Schlachter 1951 (SCH1951)",
                "Schlachter 2000 (SCH2000)",
            ],
        ),
        (
            "\u2014Espa\xf1ol (ES)\u2014",
            [
                "La Biblia de las Am\xe9ricas (LBLA)",
                "Dios Habla Hoy (DHH)",
                "Jubilee Bible 2000 (Spanish) (JBS)",
                "Nueva Biblia al D\xeda (NBD)",
                "Nueva Biblia Latinoamericana de Hoy (NBLH)",
                "Nueva Traducci\xf3n Viviente (NTV)",
                "Nueva Versi\xf3n Internacional (NVI)",
                "Nueva Versi\xf3n Internacional (Castilian) (CST)",
                "Palabra de Dios para Todos (PDT)",
                "La Palabra (Espa\xf1a) (BLP)",
                "La Palabra (Hispanoam\xe9rica) (BLPH)",
                "Reina Valera Contempor\xe1nea (RVC)",
                "Reina-Valera 1960 (RVR1960)",
                "Reina Valera 1977 (RVR1977)",
                "Reina-Valera 1995 (RVR1995)",
                "Reina-Valera Antigua (RVA)",
                "Traducci\xf3n en lenguaje actual (TLA)",
            ],
        ),
        ("\u2014Suomi (FI)\u2014", ["Raamattu 1933/38 (R1933)"]),
        (
            "\u2014Fran\xe7ais (FR)\u2014",
            [
                "La Bible du Semeur (BDS)",
                "Louis Segond (LSG)",
                "Nouvelle Edition de Gen\xe8ve \u2013 NEG1979 (NEG1979)",
                "Segond 21 (SG21)",
            ],
        ),
        (
            "\u2014\u039a\u03bf\u03b9\u03bd\u03b7 (GRC)\u2014",
            [
                "1550 Stephanus New Testament (TR1550)",
                "1881 Westcott-Hort New Testament (WHNU)",
                "1894 Scrivener New Testament (TR1894)",
                "SBL Greek New Testament (SBLGNT)",
            ],
        ),
        (
            "\u2014\u05e2\u05d1\u05e8\u05d9\u05ea (HE)\u2014",
            [
                "Habrit Hakhadasha/Haderekh (HHH)",
                "The Westminster Leningrad Codex (WLC)",
            ],
        ),
        (
            "\u2014\u0939\u093f\u0928\u094d\u0926\u0940 (HI)\u2014",
            ["Hindi Bible: Easy-to-Read Version (ERV-HI)"],
        ),
        ("\u2014Ilonggo (HIL)\u2014", ["Ang Pulong Sang Dios (HLGN)"]),
        (
            "\u2014Hrvatski (HR)\u2014",
            [
                "Hrvatski Novi Zavjet \u2013 Rijeka 2001 (HNZ-RI)",
                "Knijga O Kristu (CRO)",
            ],
        ),
        ("\u2014Krey\xf2l ayisyen (HT)\u2014", ["Haitian Creole Version (HCV)"]),
        (
            "\u2014Magyar (HU)\u2014",
            [
                "Hungarian K\xe1roli (KAR)",
                "Hungarian Bible: Easy-to-Read Version (ERV-HU)",
                "Hungarian New Translation (NT-HU)",
            ],
        ),
        ("\u2014Hawai\u2018i Pidgin (HWC)\u2014", ["Hawai\u2018i Pidgin (HWP)"]),
        ("\u2014\xcdslenska (IS)\u2014", ["Icelandic Bible (ICELAND)"]),
        (
            "\u2014Italiano (IT)\u2014",
            [
                "La Bibbia della Gioia (BDG)",
                "Conferenza Episcopale Italiana (CEI)",
                "La Nuova Diodati (LND)",
                "Nuova Riveduta 1994 (NR1994)",
                "Nuova Riveduta 2006 (NR2006)",
            ],
        ),
        ("\u2014Jacalteco, Oriental (JAC)\u2014", ["Jacalteco, Oriental (JAC)"]),
        ("\u2014Kekchi (KEK)\u2014", ["Kekchi (KEK)"]),
        ("\u2014Latina (LA)\u2014", ["Biblia Sacra Vulgata (VULGATE)"]),
        ("\u2014M\u0101ori (MI)\u2014", ["Maori Bible (MAORI)"]),
        (
            "\u2014\u041c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 (MK)\u2014",
            ["Macedonian New Testament (MNT)"],
        ),
        (
            "\u2014\u092e\u0930\u093e\u0920\u0940 (MR)\u2014",
            ["Marathi Bible: Easy-to-Read Version (ERV-MR)"],
        ),
        ("\u2014Mam, Central (MVC)\u2014", ["Mam, Central (MVC)"]),
        (
            "\u2014Mam, Todos Santos (MVJ)\u2014",
            ["Mam de Todos Santos Chuchumat\xe1n (MVJ)"],
        ),
        ("\u2014Plautdietsch (NDS)\u2014", ["Reimer 2001 (REIMER)"]),
        (
            "\u2014\u0928\u0947\u092a\u093e\u0932\u0940 (NE)\u2014",
            ["Nepali Bible: Easy-to-Read Version (ERV-NE)"],
        ),
        ("\u2014N\xe1huatl de Guerrero (NGU)\u2014", ["N\xe1huatl de Guerrero (NGU)"]),
        ("\u2014Nederlands (NL)\u2014", ["Het Boek (HTB)"]),
        (
            "\u2014Norsk (NO)\u2014",
            ["Det Norsk Bibelselskap 1930 (DNB1930)", "En Levende Bok (LB)"],
        ),
        (
            "\u2014\u0b13\u0b21\u0b3c\u0b3f\u0b06 (OR)\u2014",
            ["Oriya Bible: Easy-to-Read Version (ERV-OR)"],
        ),
        (
            "\u2014\u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40 (PA)\u2014",
            ["Punjabi Bible: Easy-to-Read Version (ERV-PA)"],
        ),
        (
            "\u2014Polski (PL)\u2014",
            [
                "Nowe Przymierze (NP)",
                "S\u0142owo \u017bycia (SZ-PL)",
                "Updated Gda\u0144sk Bible (UBG)",
            ],
        ),
        ("\u2014Nawat (PPL)\u2014", ["Ne Bibliaj Tik Nawat (NBTN)"]),
        (
            "\u2014Portugu\xeas (PT)\u2014",
            [
                "Almeida Revista e Corrigida 2009 (ARC)",
                "Nova Tradu\u04ab\xe3o na Linguagem de Hoje 2000 (NTLH)",
                "Nova Vers\xe3o Internacional (NVI-PT)",
                "O Livro (OL)",
                "Portuguese New Testament: Easy-to-Read Version (VFL)",
            ],
        ),
        ("\u2014Quichua (QU)\u2014", ["Mushuj Testamento Diospaj Shimi (MTDS)"]),
        (
            "\u2014Quich\xe9, Centro Occidenta (QUT)\u2014",
            ["Quich\xe9, Centro Occidental (QUT)"],
        ),
        (
            "\u2014Rom\xe2n\u0103 (RO)\u2014",
            [
                "Cornilescu 1924 - Revised 2010, 2014 (RMNN)",
                "Nou\u0103 Traducere \xcen Limba Rom\xe2n\u0103 (NTLR)",
            ],
        ),
        (
            "\u2014\u0420\u0443\u0441\u0441\u043a\u0438\u0439 (RU)\u2014",
            [
                "New Russian Translation (NRT)",
                "\u0421\u0432\u044f\u0449\u0435\u043d\u043d\u043e\u0435 \u041f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0412\u043e\u0441\u0442\u043e\u0447\u043d\u044b\u0439 \u041f\u0435\u0440\u0435\u0432\u043e\u0434) (CARS)",
                "\u0421\u0432\u044f\u0449\u0435\u043d\u043d\u043e\u0435 \u041f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0412\u043e\u0441\u0442\u043e\u0447\u043d\u044b\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434), \u0432\u0435\u0440\u0441\u0438\u044f \u0434\u043b\u044f \u0422\u0430\u0434\u0436\u0438\u043a\u0438\u0441\u0442\u0430\u043d\u0430 (CARST)",
                "\u0421\u0432\u044f\u0449\u0435\u043d\u043d\u043e\u0435 \u041f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0412\u043e\u0441\u0442\u043e\u0447\u043d\u044b\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434), \u0432\u0435\u0440\u0441\u0438\u044f \u0441 \xab\u0410\u043b\u043b\u0430\u0445\u043e\u043c\xbb (CARSA)",
                "Russian New Testament: Easy-to-Read Version (ERV-RU)",
                "Russian Synodal Version (RUSV)",
            ],
        ),
        ("\u2014Sloven\u010dina (SK)\u2014", ["N\xe1dej pre kazd\xe9ho (NPK)"]),
        ("\u2014Somali (SO)\u2014", ["Somali Bible (SOM)"]),
        ("\u2014Shqip (SQ)\u2014", ["Albanian Bible (ALB)"]),
        (
            "\u2014\u0421\u0440\u043f\u0441\u043a\u0438 (SR)\u2014",
            ["Serbian New Testament: Easy-to-Read Version (ERV-SR)"],
        ),
        (
            "\u2014Svenska (SV)\u2014",
            [
                "Nya Levande Bibeln (SVL)",
                "Svenska 1917 (SV1917)",
                "Svenska Folkbibeln (SFB)",
                "Svenska Folkbibeln 2014 (SFB2014)",
            ],
        ),
        ("\u2014Kiswahili (SW)\u2014", ["Neno: Bibilia Takatifu (SNT)"]),
        (
            "\u2014\u0ba4\u0bae\u0bbf\u0bb4\u0bcd (TA)\u2014",
            ["Tamil Bible: Easy-to-Read Version (ERV-TA)"],
        ),
        (
            "\u2014\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22 (TH)\u2014",
            [
                "Thai New Contemporary Bible (TNCV)",
                "Thai New Testament: Easy-to-Read Version (ERV-TH)",
            ],
        ),
        (
            "\u2014Tagalog (TL)\u2014",
            ["Ang Dating Biblia (1905) (ADB1905)", "Ang Salita ng Diyos (SND)"],
        ),
        ("\u2014Twi (TWI)\u2014", ["Nkwa Asem (NA-TWI)"]),
        (
            "\u2014\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430 (UK)\u2014",
            [
                "Ukrainian Bible (UKR)",
                "Ukrainian New Testament: Easy-to-Read Version (ERV-UK)",
            ],
        ),
        (
            "\u2014\u0627\u0631\u062f\u0648 (UR)\u2014",
            ["Urdu Bible: Easy-to-Read Version (ERV-UR)"],
        ),
        ("\u2014Uspanteco (USP)\u2014", ["Uspanteco (USP)"]),
        (
            "\u2014Ti\xeang Vi\xeat (VI)\u2014",
            [
                "1934 Vietnamese Bible (VIET)",
                "B\u1ea3n D\u1ecbch 2011 (BD2011)",
                "Vietnamese Bible: Easy-to-Read Version (BPT)",
            ],
        ),
    ]
)
VERSION_LOOKUP = {
    "Hungarian K\xe1roli (KAR)": "KAR",
    "Maori Bible (MAORI)": "MAORI",
    "Russian Synodal Version (RUSV)": "RUSV",
    "La Biblia de las Am\xe9ricas (LBLA)": "LBLA",
    "Expanded Bible (EXB)": "EXB",
    "Nouvelle Edition de Gen\xe8ve \u2013 NEG1979 (NEG1979)": "NEG1979",
    "Chinese Standard Bible (Traditional) (CSBT)": "CSBT",
    "Mounce Reverse-Interlinear New Testament (MOUNCE)": "MOUNCE",
    "Chinese Union Version Modern Punctuation (Traditional) (CUVMPT)": "CUVMPT",
    "Mushuj Testamento Diospaj Shimi (MTDS)": "MTDS",
    "Urdu Bible: Easy-to-Read Version (ERV-UR)": "ERV-UR",
    "New Life Version (NLV)": "NLV",
    "New Russian Translation (NRT)": "NRT",
    "Uspanteco (USP)": "USP",
    "New American Standard Bible (NASB)": "NASB",
    "Young's Literal Translation (YLT)": "YLT",
    "Names of God Bible (NOG)": "NOG",
    "Chinese Union Version Modern Punctuation (Simplified) (CUVMPS)": "CUVMPS",
    "Wycliffe Bible (WYC)": "WYC",
    "English Standard Version Anglicised (ESVUK)": "ESVUK",
    "Reina Valera Contempor\xe1nea (RVC)": "RVC",
    "Knijga O Kristu (CRO)": "CRO",
    "Amplified Bible (AMP)": "AMP",
    "Worldwide English (New Testament) (WE)": "WE",
    "Dette er Biblen p\xe5 dansk (DN1933)": "DN1933",
    "1550 Stephanus New Testament (TR1550)": "TR1550",
    "Conferenza Episcopale Italiana (CEI)": "CEI",
    "Bulgarian Bible (BULG)": "BULG",
    "Hindi Bible: Easy-to-Read Version (ERV-HI)": "ERV-HI",
    "BRG Bible (BRG)": "BRG",
    "Svenska Folkbibeln (SFB)": "SFB",
    "Nuova Riveduta 1994 (NR1994)": "NR1994",
    "Neno: Bibilia Takatifu (SNT)": "SNT",
    "Mam, Central (MVC)": "MVC",
    "Biblia Sacra Vulgata (VULGATE)": "VULGATE",
    "Mam de Todos Santos Chuchumat\xe1n (MVJ)": "MVJ",
    "Updated Gda\u0144sk Bible (UBG)": "UBG",
    "\u0421\u0432\u044f\u0449\u0435\u043d\u043d\u043e\u0435 \u041f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0412\u043e\u0441\u0442\u043e\u0447\u043d\u044b\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434), \u0432\u0435\u0440\u0441\u0438\u044f \u0434\u043b\u044f \u0422\u0430\u0434\u0436\u0438\u043a\u0438\u0441\u0442\u0430\u043d\u0430 (CARST)": "CARST",
    "Reina-Valera Antigua (RVA)": "RVA",
    "Revised Standard Version Catholic Edition (RSVCE)": "RSVCE",
    "Ang Dating Biblia (1905) (ADB1905)": "ADB1905",
    "Cherokee New Testament (CHR)": "CHR",
    "Vietnamese Bible: Easy-to-Read Version (BPT)": "BPT",
    "En Levende Bok (LB)": "LB",
    "Ukrainian Bible (UKR)": "UKR",
    "Schlachter 1951 (SCH1951)": "SCH1951",
    "Cakchiquel Occidental (CKW)": "CKW",
    "Revised Standard Version (RSV)": "RSV",
    "GOD\u2019S WORD Translation (GW)": "GW",
    "Dios Habla Hoy (DHH)": "DHH",
    "Lexham English Bible (LEB)": "LEB",
    "Hrvatski Novi Zavjet \u2013 Rijeka 2001 (HNZ-RI)": "HNZ-RI",
    "La Palabra (Espa\xf1a) (BLP)": "BLP",
    "Jacalteco, Oriental (JAC)": "JAC",
    "The Westminster Leningrad Codex (WLC)": "WLC",
    "Punjabi Bible: Easy-to-Read Version (ERV-PA)": "ERV-PA",
    "Nuova Riveduta 2006 (NR2006)": "NR2006",
    "Nepali Bible: Easy-to-Read Version (ERV-NE)": "ERV-NE",
    "Chinese Union Version (Simplified) (CUVS)": "CUVS",
    "\u0421\u0432\u044f\u0449\u0435\u043d\u043d\u043e\u0435 \u041f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0412\u043e\u0441\u0442\u043e\u0447\u043d\u044b\u0439 \u041f\u0435\u0440\u0435\u0432\u043e\u0434) (CARS)": "CARS",
    "Portuguese New Testament: Easy-to-Read Version (VFL)": "VFL",
    "Somali Bible (SOM)": "SOM",
    "Schlachter 2000 (SCH2000)": "SCH2000",
    "Traducci\xf3n en lenguaje actual (TLA)": "TLA",
    "Thai New Testament: Easy-to-Read Version (ERV-TH)": "ERV-TH",
    "Complete Jewish Bible (CJB)": "CJB",
    "La Nuova Diodati (LND)": "LND",
    "Chinese New Testament: Easy-to-Read Version (ERV-ZH)": "ERV-ZH",
    "Ang Pulong Sa Dios (APSD-CEB)": "APSD-CEB",
    "Nueva Biblia al D\xeda (NBD)": "NBD",
    "Nueva Biblia Latinoamericana de Hoy (NBLH)": "NBLH",
    "Contemporary English Version (CEV)": "CEV",
    "La Palabra (Hispanoam\xe9rica) (BLPH)": "BLPH",
    "New English Translation (NET Bible)": "NET",
    "New International Reader's Version (NIRV)": "NIRV",
    "New Revised Standard Version, Anglicised (NRSVA)": "NRSVA",
    "Svenska 1917 (SV1917)": "SV1917",
    "New International Version - UK (NIVUK)": "NIVUK",
    "1894 Scrivener New Testament (TR1894)": "TR1894",
    "The Voice (VOICE)": "VOICE",
    "Bulgarian New Testament: Easy-to-Read Version (ERV-BG)": "ERV-BG",
    "Reina Valera 1977 (RVR1977)": "RVR1977",
    "Russian New Testament: Easy-to-Read Version (ERV-RU)": "ERV-RU",
    "Chinese Standard Bible (Simplified) (CSBS)": "CSBS",
    "N\xe1dej pre kazd\xe9ho (NPK)": "NPK",
    "\u0421\u0432\u044f\u0449\u0435\u043d\u043d\u043e\u0435 \u041f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0412\u043e\u0441\u0442\u043e\u0447\u043d\u044b\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434), \u0432\u0435\u0440\u0441\u0438\u044f \u0441 \xab\u0410\u043b\u043b\u0430\u0445\u043e\u043c\xbb (CARSA)": "CARSA",
    "Hawai\u2018i Pidgin (HWP)": "HWP",
    "Nkwa Asem (NA-TWI)": "NA-TWI",
    "Hungarian Bible: Easy-to-Read Version (ERV-HU)": "ERV-HU",
    "Reina-Valera 1960 (RVR1960)": "RVR1960",
    "Serbian New Testament: Easy-to-Read Version (ERV-SR)": "ERV-SR",
    "Bibelen p\xe5 hverdagsdansk (BPH)": "BPH",
    "Nou\u0103 Traducere \xcen Limba Rom\xe2n\u0103 (NTLR)": "NTLR",
    "Awadhi Bible: Easy-to-Read Version (ERV-AWA)": "ERV-AWA",
    "English Standard Version (ESV)": "ESV",
    "Thai New Contemporary Bible (TNCV)": "TNCV",
    "Segond 21 (SG21)": "SG21",
    "King James Version (KJV)": "KJV",
    "International Standard Version (ISV)": "ISV",
    "Bible 21 (B21)": "B21",
    "Luther Bibel 1545 (LUTH1545)": "LUTH1545",
    "Reina-Valera 1995 (RVR1995)": "RVR1995",
    "Haitian Creole Version (HCV)": "HCV",
    "Palabra de Dios para Todos (PDT)": "PDT",
    "La Bible du Semeur (BDS)": "BDS",
    "Macedonian New Testament (MNT)": "MNT",
    "B\u1ea3n D\u1ecbch 2011 (BD2011)": "BD2011",
    "La Bibbia della Gioia (BDG)": "BDG",
    "American Standard Version (ASV)": "ASV",
    "Raamattu 1933/38 (R1933)": "R1933",
    "1599 Geneva Bible (GNV)": "GNV",
    "World English Bible (WEB)": "WEB",
    "Easy-to-Read Version (ERV)": "ERV",
    "Amplified Bible, Classic Edition (AMPC)": "AMPC",
    "Beibl William Morgan (BWM)": "BWM",
    "New American Bible (Revised Edition) (NABRE)": "NABRE",
    "Nya Levande Bibeln (SVL)": "SVL",
    "Amuzgo de Guerrero (AMU)": "AMU",
    "Ang Pulong Sang Dios (HLGN)": "HLGN",
    "Modern English Version (MEV)": "MEV",
    "Hoffnung f\xfcr Alle (HOF)": "HOF",
    "New Revised Standard Version, Anglicised Catholic Edition (NRSVACE)": "NRSVACE",
    "Neue Genfer \xdcbersetzung (NGU-DE)": "NGU-DE",
    "Oriya Bible: Easy-to-Read Version (ERV-OR)": "ERV-OR",
    "1940 Bulgarian Bible (BG1940)": "BG1940",
    "Slovo na cestu (SNC)": "SNC",
    "New Revised Standard Version Catholic Edition (NRSVCE)": "NRSVCE",
    "New Revised Standard Version Updated Edition (NRSVUE)": "NRSVUE",
    "Common English Bible (CEB)": "CEB",
    "Chinese Union Version (Traditional) (CUV)": "CUV",
    "New International Version (NIV)": "NIV",
    "New Century Version (NCV)": "NCV",
    "Quich\xe9, Centro Occidental (QUT)": "QUT",
    "Svenska Folkbibeln 2014 (SFB2014)": "SFB2014",
    "Ketab El Hayat (NAV)": "NAV",
    "21st Century King James Version (KJ21)": "KJ21",
    "Kekchi (KEK)": "KEK",
    "Chinanteco de Comaltepec (CCO)": "CCO",
    "Reimer 2001 (REIMER)": "REIMER",
    "Marathi Bible: Easy-to-Read Version (ERV-MR)": "ERV-MR",
    "Louis Segond (LSG)": "LSG",
    "O Livro (OL)": "OL",
    "Holman Christian Standard Bible (HCSB)": "HCSB",
    "1934 Vietnamese Bible (VIET)": "VIET",
    "Albanian Bible (ALB)": "ALB",
    "The Message (MSG)": "MSG",
    "Hungarian New Translation (NT-HU)": "NT-HU",
    "Bulgarian Protestant Bible (BPB)": "BPB",
    "1881 Westcott-Hort New Testament (WHNU)": "WHNU",
    "Het Boek (HTB)": "HTB",
    "Ne Bibliaj Tik Nawat (NBTN)": "NBTN",
    "Arabic Bible: Easy-to-Read Version (ERV-AR)": "ERV-AR",
    "Almeida Revista e Corrigida 2009 (ARC)": "ARC",
    "Living Bible (TLB)": "TLB",
    "SBL Greek New Testament (SBLGNT)": "SBLGNT",
    "Orthodox Jewish Bible (OJB)": "OJB",
    "Det Norsk Bibelselskap 1930 (DNB1930)": "DNB1930",
    "New Living Translation (NLT)": "NLT",
    "International Children\u2019s Bible (ICB)": "ICB",
    "Nowe Przymierze (NP)": "NP",
    "N\xe1huatl de Guerrero (NGU)": "NGU",
    "Nova Tradu\u04ab\xe3o na Linguagem de Hoje 2000 (NTLH)": "NTLH",
    "Chinese Contemporary Bible (CCB)": "CCB",
    "Jubilee Bible 2000 (Spanish) (JBS)": "JBS",
    "Icelandic Bible (ICELAND)": "ICELAND",
    "Nueva Versi\xf3n Internacional (NVI)": "NVI",
    "Tamil Bible: Easy-to-Read Version (ERV-TA)": "ERV-TA",
    "Nova Vers\xe3o Internacional (NVI-PT)": "NVI-PT",
    "J.B. Phillips New Testament (PHILLIPS)": "PHILLIPS",
    "Habrit Hakhadasha/Haderekh (HHH)": "HHH",
    "Darby Translation (DARBY)": "DARBY",
    "Ukrainian New Testament: Easy-to-Read Version (ERV-UK)": "ERV-UK",
    "Authorized (King James) Version (AKJV)": "AKJV",
    "Chinese New Version (Traditional) (CNVT)": "CNVT",
    "Cornilescu 1924 - Revised 2010, 2014 (RMNN)": "RMNN",
    "S\u0142owo \u017bycia (SZ-PL)": "SZ-PL",
    "Disciples\u2019 Literal New Testament (DLNT)": "DLNT",
    "Ang Salita ng Diyos (SND)": "SND",
    "Good News Translation (GNT)": "GNT",
    "Nueva Traducci\xf3n Viviente (NTV)": "NTV",
    "New Revised Standard Version (NRSV)": "NRSV",
    "Douay-Rheims 1899 American Edition (DRA)": "DRA",
    "Chinese New Version (Simplified) (CNVS)": "CNVS",
    "Jubilee Bible 2000 (JUB)": "JUB",
    "New King James Version (NKJV)": "NKJV",
    "Nueva Versi\xf3n Internacional (Castilian) (CST)": "CST",
}
VERSIONS = VERSION_LOOKUP.values()
BOOKS = (
    "genesis",
    "exodus",
    "leviticus",
    "numbers",
    "deuteronomy",
    "joshua",
    "judges",
    "ruth",
    "1samuel",
    "2samuel",
    "1kings",
    "2kings",
    "1chronicles",
    "2chronicles",
    "ezra",
    "nehemiah",
    "esther",
    "job",
    "psalm",
    "proverbs",
    "ecclesiastes",
    "songofsolomon",
    "isaiah",
    "jeremiah",
    "lamentations",
    "ezekiel",
    "daniel",
    "hosea",
    "joel",
    "amos",
    "obadiah",
    "jonah",
    "micah",
    "nahum",
    "habakkuk",
    "zephaniah",
    "haggai",
    "zechariah",
    "malachi",
    "matthew",
    "mark",
    "luke",
    "john",
    "acts",
    "romans",
    "1corinthians",
    "2corinthians",
    "galatians",
    "ephesians",
    "philippians",
    "colossians",
    "1thessalonians",
    "2thessalonians",
    "1timothy",
    "2timothy",
    "titus",
    "philemon",
    "hebrews",
    "james",
    "1peter",
    "2peter",
    "1john",
    "2john",
    "3john",
    "jude",
    "revelation",
)

APOCRYPHA_BOOK_DATA = (
    {"title": "Tobit", "slug": "tobit", "aliases": ("tobit", "tob")},
    {"title": "Judith", "slug": "judith", "aliases": ("judith", "jdt")},
    {
        "title": "Additions to Esther",
        "slug": "additionstoesther",
        "aliases": ("additions to esther", "greek esther"),
    },
    {
        "title": "Wisdom",
        "slug": "wisdom",
        "aliases": ("wisdom", "wisdom of solomon", "wis"),
    },
    {
        "title": "Sirach",
        "slug": "sirach",
        "aliases": ("sirach", "ecclesiasticus", "sir"),
    },
    {"title": "Baruch", "slug": "baruch", "aliases": ("baruch", "bar")},
    {
        "title": "Letter of Jeremiah",
        "slug": "letterofjeremiah",
        "aliases": ("letter of jeremiah", "epistle of jeremiah"),
    },
    {
        "title": "Prayer of Azariah",
        "slug": "prayerofazariah",
        "aliases": ("prayer of azariah",),
    },
    {"title": "Susanna", "slug": "susanna", "aliases": ("susanna",)},
    {
        "title": "Bel and the Dragon",
        "slug": "belandthedragon",
        "aliases": ("bel and the dragon",),
    },
    {
        "title": "Prayer of Manasseh",
        "slug": "prayerofmanasseh",
        "aliases": ("prayer of manasseh",),
    },
    {"title": "1 Esdras", "slug": "1esdras", "aliases": ("1 esdras", "1esdras")},
    {"title": "2 Esdras", "slug": "2esdras", "aliases": ("2 esdras", "2esdras")},
    {
        "title": "1 Maccabees",
        "slug": "1maccabees",
        "aliases": ("1 maccabees", "1maccabees", "i maccabees"),
    },
    {
        "title": "2 Maccabees",
        "slug": "2maccabees",
        "aliases": ("2 maccabees", "2maccabees", "ii maccabees"),
    },
    {"title": "Psalm 151", "slug": "psalm151", "aliases": ("psalm 151", "ps151")},
)

APOCRYPHA_BOOK_SLUGS = tuple(book["slug"] for book in APOCRYPHA_BOOK_DATA)
APOCRYPHA_VERSION_CODES = frozenset(
    {
        "CEB",
        "DHH",
        "DRA",
        "GNT",
        "NABRE",
        "NCB",
        "NRSVA",
        "NRSVACE",
        "NRSVCE",
        "NRSVUE",
        "RSV",
        "RSVCE",
        "TLA",
        "WYC",
    }
)
CORE_DEUTEROCANON_BOOK_TITLES = frozenset(
    {
        "Tobit",
        "Judith",
        "Additions to Esther",
        "Wisdom",
        "Sirach",
        "Baruch",
        "Letter of Jeremiah",
        "Prayer of Azariah",
        "Susanna",
        "Bel and the Dragon",
        "1 Maccabees",
        "2 Maccabees",
    }
)
EXTENDED_APOCRYPHA_BOOK_TITLES = frozenset(
    CORE_DEUTEROCANON_BOOK_TITLES
    | {
        "1 Esdras",
        "2 Esdras",
        "Prayer of Manasseh",
        "Psalm 151",
    }
)
VERSION_SUPPORTED_APOCRYPHA_BOOKS = {
    "CEB": CORE_DEUTEROCANON_BOOK_TITLES,
    "DHH": CORE_DEUTEROCANON_BOOK_TITLES,
    "DRA": CORE_DEUTEROCANON_BOOK_TITLES,
    "GNT": CORE_DEUTEROCANON_BOOK_TITLES,
    "NABRE": CORE_DEUTEROCANON_BOOK_TITLES,
    "NCB": CORE_DEUTEROCANON_BOOK_TITLES,
    "NRSV": EXTENDED_APOCRYPHA_BOOK_TITLES,
    "NRSVA": EXTENDED_APOCRYPHA_BOOK_TITLES,
    "NRSVACE": CORE_DEUTEROCANON_BOOK_TITLES,
    "NRSVCE": CORE_DEUTEROCANON_BOOK_TITLES,
    "NRSVUE": EXTENDED_APOCRYPHA_BOOK_TITLES,
    "RSV": EXTENDED_APOCRYPHA_BOOK_TITLES,
    "RSVCE": CORE_DEUTEROCANON_BOOK_TITLES,
    "TLA": CORE_DEUTEROCANON_BOOK_TITLES,
    "WYC": CORE_DEUTEROCANON_BOOK_TITLES,
}
BOOKS = BOOKS + APOCRYPHA_BOOK_SLUGS
